name: Build Docker Image

on:
  push:
    branches:
      - 'jobrad-**'
    tags:
      - 'jobrad-**'

jobs:

  build-docker:
    runs-on: [self-hosted, short]
    permissions:
      contents: read
      packages: write
    env:
      GHCR_IMAGE_NAME: ghcr.io/jobrad-gmbh/odoo
      ARTIFACTORY_IMAGE_NAME: artifactory.service.jobrad.org/jra_docker_registry/odoo
    steps:
    - uses: actions/checkout@v3

    - name: Create variables
      shell: bash
      run: |
        echo "BRANCH_NAME=$(echo ${GITHUB_REF} | sed 's/refs\/heads\///'  | sed 's/refs\/tags\///' | sed 's/\//_/g')" >> $GITHUB_ENV
        echo "SHORT_REV=$(echo ${{ github.sha }})" >> $GITHUB_ENV

    - name: Login to ghcr registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to artifactory registry
      uses: docker/login-action@v2
      with:
        registry: artifactory.service.jobrad.org
        username: github_runner
        password: ${{ secrets.ARTIFACTORY_TOKEN }}

    - name: Install Docker Buildx
      run: |
        mkdir -p ~/.docker/cli-plugins
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --use --name mybuilder
        docker buildx inspect --bootstrap

    - name: Build the Docker image
      shell: bash
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 --push -f docker/Dockerfile --build-arg ODOO_BASE_IMAGE_TAG=${BRANCH_NAME} -t ${GHCR_IMAGE_NAME}:${SHORT_REV} -t ${GHCR_IMAGE_NAME}:${BRANCH_NAME} -t ${ARTIFACTORY_IMAGE_NAME}:${SHORT_REV} -t ${ARTIFACTORY_IMAGE_NAME}:${BRANCH_NAME} .
