name: Build Docker Image

on:
  push:
    branches:
      - 'jobrad-**'
    tags:
      - 'jobrad-**'

jobs:

  build-docker:
    runs-on: [self-hosted, short]
    permissions:
      contents: read
      packages: write
    env:
      GHCR_IMAGE_NAME: ghcr.io/jobrad-gmbh/odoo
      ARTIFACTORY_IMAGE_NAME: artifactory.service.jobrad.org/jra_docker_registry/odoo
    steps:
    - uses: actions/checkout@v3

    - name: Create variables
      shell: bash
      run: |
        echo "BRANCH_NAME=$(echo ${GITHUB_REF} | sed 's/refs\/heads\///'  | sed 's/refs\/tags\///' | sed 's/\//_/g')" >> $GITHUB_ENV
        echo "SHORT_REV=$(echo ${{ github.sha }})" >> $GITHUB_ENV

    - name: Login to ghcr registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to artifactory registry
      uses: docker/login-action@v2
      with:
        registry: artifactory.service.jobrad.org
        username: github_runner
        password: ${{ secrets.ARTIFACTORY_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker images
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        build-args:
          - ODOO_BASE_IMAGE_TAG=${BRANCH_NAME}
        tags: |
          ${{GHCR_IMAGE_NAME}}:${{SHORT_REV}}
          ${{GHCR_IMAGE_NAME}}:${{BRANCH_NAME}}
          ${{ARTIFACTORY_IMAGE_NAME}}:${{SHORT_REV}}
          ${{ARTIFACTORY_IMAGE_NAME}}:${{BRANCH_NAME}}
          